#python run_subprocess.py TraditionalSCV 0.0
#python run_subprocess.py Optimistic 0.0
python run_subprocess.py RegGBSCV 0.0
python run_subprocess.py RegGBSCV 0.1
python run_subprocess.py RegGBSCV 0.2
python run_subprocess.py RegGBSCV 0.3
python run_subprocess.py RegGBSCV 0.4
python run_subprocess.py RegGBSCV 0.5
python run_subprocess.py RegGBSCV 0.6
python run_subprocess.py RegGBSCV 0.7
python run_subprocess.py RegGBSCV 0.8
python run_subprocess.py RegGBSCV 0.9
python run_subprocess.py RegGBSCV 1.0
