python run_subprocess.py CrossValidation 0.0 KNN CFS
python run_subprocess.py CrossValidation 0.0 OLS CFS
python run_subprocess.py CrossValidation 0.0 Lasso CFS
python run_subprocess.py CrossValidation 0.0 Ridge CFS
python run_subprocess.py CrossValidation 0.0 ElasticNet CFS
python run_subprocess.py CrossValidation 0.0 DT CFS
python run_subprocess.py CrossValidation 0.0 LGBM CFS
python run_subprocess.py CrossValidation 0.0 RF CFS
python run_subprocess.py CrossValidation 0.0 MLP CFS
python run_subprocess.py CrossValidation 0.0 SVM CFS
echo 1
python run_subprocess.py TraditionalSCV 0.0 KNN CFS
python run_subprocess.py TraditionalSCV 0.0 OLS CFS
python run_subprocess.py TraditionalSCV 0.0 Lasso CFS
python run_subprocess.py TraditionalSCV 0.0 Ridge CFS
python run_subprocess.py TraditionalSCV 0.0 ElasticNet CFS
python run_subprocess.py TraditionalSCV 0.0 DT CFS
python run_subprocess.py TraditionalSCV 0.0 LGBM CFS
python run_subprocess.py TraditionalSCV 0.0 RF CFS
python run_subprocess.py TraditionalSCV 0.0 MLP CFS
python run_subprocess.py TraditionalSCV 0.0 SVM CFS
echo Optimistic
python run_subprocess.py Optimistic 0.0 KNN CFS
python run_subprocess.py Optimistic 0.0 OLS CFS
python run_subprocess.py Optimistic 0.0 Lasso CFS
python run_subprocess.py Optimistic 0.0 Ridge CFS
python run_subprocess.py Optimistic 0.0 ElasticNet CFS
python run_subprocess.py Optimistic 0.0 DT CFS
python run_subprocess.py Optimistic 0.0 LGBM CFS
python run_subprocess.py Optimistic 0.0 RF CFS
python run_subprocess.py Optimistic 0.0 MLP CFS
python run_subprocess.py Optimistic 0.0 SVM CFS
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.0 KNN CFS
python run_subprocess.py RegGBSCV 0.0 OLS CFS
python run_subprocess.py RegGBSCV 0.0 Lasso CFS
python run_subprocess.py RegGBSCV 0.0 Ridge CFS
python run_subprocess.py RegGBSCV 0.0 ElasticNet CFS
python run_subprocess.py RegGBSCV 0.0 DT CFS
python run_subprocess.py RegGBSCV 0.0 LGBM CFS
python run_subprocess.py RegGBSCV 0.0 RF CFS
python run_subprocess.py RegGBSCV 0.0 MLP CFS
python run_subprocess.py RegGBSCV 0.0 SVM CFS