#python run_subprocess.py TraditionalSCV 0.0 KNN
#python run_subprocess.py TraditionalSCV 0.0 OLS
#python run_subprocess.py TraditionalSCV 0.0 Lasso
#python run_subprocess.py TraditionalSCV 0.0 Ridge
#python run_subprocess.py TraditionalSCV 0.0 ElasticNet
#python run_subprocess.py TraditionalSCV 0.0 DT
python run_subprocess.py TraditionalSCV 0.0 LGBM
python run_subprocess.py TraditionalSCV 0.0 RF
python run_subprocess.py TraditionalSCV 0.0 MLP
python run_subprocess.py TraditionalSCV 0.0 SVM