echo Brazil_election
#python run_subprocess.py Brazil_Election_2018 Optimistic
#python run_subprocess.py Brazil_Election_2018 TraditionalSCV
python run_subprocess.py Brazil_Election_2018 CrossValidation
